### ISSUE TITLE
Error while use with Compass

### ISSUE THREAD

**Issue by MiincGu** [sass/node-sass#1004]
In my sass file:
```
@include background-size(100% 100%);
```

After gulp-sass:
```
-webkit-background-size: compact(100% 100%, false, false, false, false, false, false, false, false, false);
-moz-background-size: compact(100% 100%, false, false, false, false, false, false, false, false, false);
-o-background-size: compact(100% 100%, false, false, false, false, false, false, false, false, false);
background-size: compact(100% 100%, false, false, false, false, false, false, false, false, false);
```

Seems like compact() is not excuted.

**Comment by saper** [comment]
How did you integrate node-sass with compass?

**Comment by kevva** [comment]
They aren't compatible. Either use Ruby Sass with Compass or don't use Compass at all.

**Comment by xzyfer** [comment]
`compact` was removed from Libsass in 3.0.0 because it's not part of the official Sass language spec. This function is provided to Sass via Compass. Compass is not and will not be compatible with Libsass.

You can use a polyfill from [Sassdash](http://davidkpiano.github.io/sassdash/sassdoc/index.html#function-_compact) if you wish to have this behaviour.
