### ISSUE TITLE
`require` option

### ISSUE THREAD

**Issue by srph** [sass/node-sass#1010]
Is it possible to use the original implementation's `require` option?

e.g,

```bash
sass -r sass-globbing
```

**Comment by saper** [comment]
How would you like to use it in the context of node? You might be better off by creating your own `package.json` file, I think...

**Comment by srph** [comment]
What do you mean creating my own `package.json`? I can't see how I can use sass plugins with node-sass. Is this possible at the moment?

**Comment by saper** [comment]
You cannot use `sass` plugins written in Ruby with `node-sass`, because we are using C/C++ library (https://github.com/sass/libsass) and Node.js, which runs in JavaScript. So you can pretty much script your own custom functions and custom importers in JavaScript, but you cannot use Ruby.

Please note that this feature is still experimental in the recent `node-sass`.

**Comment by srph** [comment]
Ah..huh. I see. Thanks!
