### ISSUE TITLE
Throw an obvious installation when installing with node 0.11.x

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1014]
We get a bunch issues for people having installation issues with node v0.11 that waste a lot of time.

The installation fails with cryptic `node: symbol lookup error` errors i.e. https://github.com/sass/node-sass/issues/1013

**Comment by nschonni** [comment]
Not sure if just tightening up the [`engines`](https://docs.npmjs.com/files/package.json#engines) property (and adding the "iojs" ranges) would help.

**Comment by xzyfer** [comment]
@nschonni I considered this however

> Note that, unless the user has set the engine-strict config flag, this field is advisory only.

> [engineStrict] is deprecated and will be removed in npm 3.0.0.

From my experience people don't read the output of `npm` before creating issues.

**Comment by katowulf** [comment]
In my experience, *people* read both the npm logs and the issues before creating an issue. -- a people

**Comment by saper** [comment]
Note to self on UNIX: Suppose we have a missing symbol in the library. If we load it shared library via `var = request('binding.node');`, this operation succeeds because of lazy loading of symbols. But any attempt to call anything that needs the undefined function will abort the program in the hard way - run time linker will simply `_exit(1)`:

````
$ node scripts/build.js 
` /home/saper/node_modules/node-sass/vendor/freebsd-x64-45/binding.node ` exists. 
 testing binary.
/home/saper/sw/libsass/lib/libsass.so: Undefined symbol "call_undefined"
$ echo $?
1
````

There is no way to intercept this `Undefined symbol` error. `npm` is executing another copy of `node` for our lifecycle script and checks the return code. Maybe we should do it the same way.

**Comment by xzyfer** [comment]
@katowulf you're in the minority. This issue tracker is a testament to the contrary.

@saper we can simply get away with a `process.version` check. We know installation will fail hard with 0.11 so lets catch it early.

**Comment by xzyfer** [comment]
@saper so it looks like after the `nan@2` update we now work on node@0.11. I tested locally with 0.11.6 on OSX.
