### ISSUE TITLE
Generate checksums for precompiled binaries and verify on install

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1017]
_I want to preface this by saying it's mostly a gut feeling I haven't been able to reproduce yet_

I've notice a correlation between installation related errors and minor version releases that change the precompiled binaries. I believe this to be due to projects using node-sass as a `^x` dependency.

Here is what I think is happening. 

1. User installs gulp-sass which has `node-sass@^3` as a dep
  - `node-sass@3.1.2` is installed
2. We release `node-sass@3.2.0` with a new binary set
3. User runs `npm install`
  - `node-sass` is updated to `3.2.0`
  - the install scripts sees a binary exists and doesn't download the one.

****

I've yet to reproduce this exactly set of circumstances myself because it requires using forks and git backends which may affect the result. 

I have confirmed that when using a recent `npm` packages are deleted before installed *if they're installed directly*. I haven't confirmed if this is case for transient dependencies.

***

Wether this is an issue or not I believe their is value in being 100% certain the correct binary for the given arch, os, and node-sass version is being used at all times.

I suggest we do this by generating checksums for our binaries and verifying them as part of the existing integrity check. 

**If nothing else it gives users confidence that they're not running untrusted C++ code on their machines**.

Thoughts @am11 @saper ?

**Comment by am11** [comment]
The issue is that we are trying to polyfill the limitation of runtime:

1. Binaries are not backward compatible and node-gyp doesn't provide cross-module compilation support .
2. npm doesn't have support for native dependencies (because everything is package and native bins aren't).

IMO, we can leave it as is and hope more C++-module packages will join the club and we will have better infrastructure provisioned from the upstream.

> If nothing else it gives users confidence that they're not running untrusted C++ code on their machines.

Users always have an option to compile the binary manually, in case they are having trust issues. :smile:

**Comment by xzyfer** [comment]
I've been chatting to the npm team. This is actually on purpose in npm as an optimisation. Any work around will be a pain. We now suggest people run `npm rebuild node-sass` if the binary has issues.
