### ISSUE TITLE
jxcore with node-sass

### ISSUE THREAD

**Issue by dapriett** [sass/node-sass#1080]
I'm trying to use [jxcore](http://jxcore.com/home/) but I get an error with node-sass:

`jx install node-sass`

```

> node-sass@3.2.0 install /sails-app/node_modules/node-sass
> /usr/local/bin/jx scripts/install.js

Binary downloaded and installed at /sails-app/node_modules/node-sass/vendor/darwin-x64-11/binding.node
 
> node-sass@3.2.0 postinstall /sails-app/node_modules/node-sass
> /usr/local/bin/jx scripts/build.js

` /sails-app/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
dyld: lazy symbol binding failed: Symbol not found: __ZN4node6Buffer3NewEPKcm
  Referenced from: /sails-app/node_modules/node-sass/vendor/darwin-x64-11/binding.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node6Buffer3NewEPKcm
  Referenced from: /sails-app/node_modules/node-sass/vendor/darwin-x64-11/binding.node
  Expected in: flat namespace
```

I believe it could be because the node binding is just downloaded vs compiled, using jx.

**Comment by saper** [comment]
JXCore is a node.js fork that is not supported, this is because node-sass is not a pure JavaScript module - we are using C++ bindings to JavaScript.

Your engine advertises support for binary modules API version 11 (similar to node 0.10), but it does not provide the necessary interface. 

I'd recommend trying to install node-sass with node v0.10.40 (this is what jxcore 0.3.05 claims to be) and see if it works.

I can see you have already opened https://github.com/jxcore/jxcore/issues/492 with them.
