### ISSUE TITLE
Un-quoted sass imports are not watched.

### ISSUE THREAD

**Issue by changemewtf** [sass/node-sass#1179]
With this file structure:

```
.
|-- package.json
|-- public
|   `-- index.css
`-- styles
    |-- account.sass
    `-- index.sass
```

And this code:

``` sass
/* styles/index.sass */
@import account
```

``` sass
/* styles/account.sass */
body
  background: purple
```

And this command line:

```
node-sass -wr styles/index.sass public/index.css
```

Making a change in `styles/account.sass` **will not** trigger a rebuild of `public/index.css`.

The dependency tree is cached when `node-sass` first runs, so adding quotes does not add a watch bit to `styles/account.sass` until you re-run the command. Don't be fooled by the rebuild triggered when you save `styles/index.sass` after adding quotes.

Version info:

```
$ node-sass --version
node-sass       3.3.3   (Wrapper)       [JavaScript]
libsass         3.2.5   (Sass Compiler) [C/C++]
```

**Comment by saper** [comment]
Is it better with .scss maybe?

**Comment by snuggs** [comment]
Interesting @saper however why would this even matter? File types should be superfluous. That said...I've ran into situations where  semicolons and curly braces ARE REQUIRED. which would NOT be SASS but SCSS.

That said, kinda ironic SASS recommends SCSS instead of SASS. The ruby SASS compiler allows
````sass
@import foo /* ruby sass */
@import "foo" /* this DOES work with node sass. Not without quotes */
````

Isn't node sass a port of ruby sass?

**Comment by saper** [comment]
> Interesting @saper however why would this even matter? File types should be superfluous. That said...I've ran into situations where  semicolons and curly braces ARE REQUIRED. which would NOT be SASS but SCSS.
> 
> That said, kinda ironic SASS recommends SCSS instead of SASS. The ruby SASS compiler allows
> ````sass
> @import foo /* ruby sass */
> @import "foo" /* this DOES work with node sass. Not without quotes */
> ````
> 
> Isn't node sass a port of ruby sass?

My question was not about what is right or wrong, I just wanted to see if the bug
concerns all formats or is it some problem with sass-graph not understanding indented
syntax properly.

**Comment by snuggs** [comment]
Again @saper converting to SCSS forces the requirement to use semicolons and curly braces if i'm not mistaken. /cc @mcantor

**Comment by mcantor** [comment]
I'm not at the right machine to test this, but @saper I'm assuming that switching to .scss would work because it is a syntax error to have unquoted imports in scss format.

In this case, the sass parsing process does not throw an error (because unquoted imports are valid indented syntax), but the code that generates the dependency graph seems to be running on different rules.

**Comment by saper** [comment]
Related issue https://github.com/xzyfer/sass-graph/issues/22

**Comment by saper** [comment]
So it looks like http://github.com/xzyfer/sass-graph does not support indented syntax really.

Filed https://github.com/xzyfer/sass-graph/issues/31

**Comment by saper** [comment]
Should be fixed after https://github.com/xzyfer/sass-graph/pull/70
