### ISSUE TITLE
Incompatibility between importers and includePaths?

### ISSUE THREAD

**Issue by pyrsmk** [sass/node-sass#1356]
I'm using [node-sass-json-importer](https://github.com/Updater/node-sass-json-importer) to import JSON vars into my SCSS file. But when using it (with gulp-sass), `modular-scale` variables are not reached anymore, like if my `includePaths` are not valid anymore. I debugged `node-sass-json-importer` a bit and it seems the bug doesn't come from it. It's like the `Sass.NULL` returned value is blocking `includePaths` importer.

**Comment by pmowrer** [comment]
Not sure if it's related, but I experienced a similar issue trying to dev on `node-sass-json-importer` locally with `npm-link`. `node-sass` would suddenly ignore non-json imports. 

It appears the issue stems from multiple instances of `node-sass` being loaded. Since importers must return `sass.NULL` for files they aren't processing, `node-sass` is a required dependency of importers. If this `node-sass` dependency doesn't resolve to the same instance as the one that triggered the importer in the first place, everything breaks. In my case, `npm-link`ing resulted in `node-sass-json-importer` using its own `node-sass` dependency.

Any recommendation for importer developers on how to handle this situation?

**Comment by pmowrer** [comment]
I see this is extensively covered in https://github.com/sass/node-sass/issues/1291

**Comment by xzyfer** [comment]
@pyrsmk please provide the exact steps required to reproduce this issue.

**Comment by xzyfer** [comment]
Closed to due in activity.

**Comment by pyrsmk** [comment]
Sorry, I was really busy with many projects. I had test this and the bug is now gone ;)
