### ISSUE TITLE
Unexpected breaking change for @function inside control directive

### ISSUE THREAD

**Issue by loganfsmyth** [sass/node-sass#1456]
Upon updating from `3.4.x` to `3.5.x` I'm getting

> Functions may not be defined within control directives or other mixins.

Specifically we're seeing the error because of https://github.com/Igosuki/compass-mixins/blob/master/lib/compass/functions/_lists.scss#L80

If we need to find a replacement, that's not the end of the world, but it seems like this should have necessitated a major version bump, or been a warning in the short term?

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue. 

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by xzyfer** [comment]
The following code is not valid Sass

```
@if true {
  @function foo() {
    @return false;
  }
}
```
And will result in error you're seeing
```
Functions may not be defined within control directives or other mixins.
```

This didn't error previously due to a bug. The error is the correct behaviour.

**Comment by loganfsmyth** [comment]
Sorry, my mistake.
