### ISSUE TITLE
Conditional import fails build on  3.5.* works  on 3.4.2

### ISSUE THREAD

**Issue by dlebedynskyi** [sass/node-sass#1468]
conditional import does not work now 
```
$theme-building: false !default;

@if $theme-building != true {
  @import "./colors";
}

@import "./globals";
@import "./mixins";

```
Worked fine on 3.4.2
temp fix - in package.json  
```
"node-sass": "3.4.2",
```
issue related 
https://github.com/react-toolbox/react-toolbox/issues/466

**Comment by mgreter** [comment]
[Please use the search before opening new issues] [1]!

[Long story short: "Conditional imports are not possible in Sass."] [2]

[1]: https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue+Conditional+import
[2]: https://github.com/sass/node-sass/issues/1459#issuecomment-212846976

**Comment by dlebedynskyi** [comment]
@mgreter will dive deeper into issues beyond header. ty

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. This issue is a result of invalid Sass. Node Sass has no way to know that these breakages because we assume valid Sass is being compiled. This is no different to depending on an undocumented API. For that reason we do not consider these breaking changes.

If valid Sass started breaking we would consider that a breaking change. We don't claim responsibility for bugs in the Sass code being compiled.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

In closing if your code does not compile with the official Sass project you should not expect it to compile with Node Sass.

**Comment by dlebedynskyi** [comment]
@xzyfer no problem from your side guys. Thanks for real quick updates. 
Will have to figure out workaround someway.   it just came out really unexpected for us.

**Comment by gkatsev** [comment]
As part of this, I've pinned node-sass to `3.4.2` to give us extra time to re-write out sass code to not use conditional imports, however, today, when reinstalling node-sas@3.4.2, it started failing with conditional imports. Were there any changes made to the 3.4.2 binaries?

**Comment by xzyfer** [comment]
No. Node Sass releases are immutable.

**Comment by gkatsev** [comment]
That's what I was hoping for. I'll investigate and report back why it started failing for me.

**Comment by gkatsev** [comment]
Turns out I was relying on grunt-sass in one section of the project which uses `^3.4.0` version range which installed node-sass@3.7.0.

**Comment by xzyfer** [comment]
FWIW I believe the newest grunt-sass release is now locked to ^3.7.0.
Locking to an old version of node-sass is non-trivial and means we cannot
offer support.

Regards,
Michael

**Comment by gkatsev** [comment]
Yup, thanks @xzyfer sorry for the alarm. We're locked to the old version just until we can update our code to not use conditional imports.
