### ISSUE TITLE
No-longer-silent errors should be documented

### ISSUE THREAD

**Issue by sethbrasile** [sass/node-sass#1470]
The bump to Delorean is causing builds to fail due to some errors that used to be silent now halting compile. The cause or an explanation should probably be documented on the release?

https://github.com/sass/node-sass/issues/1469

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. These issues you mention are a result of people compile invalid Sass. Node Sass has no way to know that these breakages because we assume valid Sass is being compiled.  This is no different to depending on an undocumented API. For that reason we do not consider these breaking changes.

If valid Sass started breaking we would consider that a breaking change. We don't claim responsibility for bugs in the Sass code being compiled.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

In closing if your code does not compile with the official [Sass](http://sass-lang.com/) project you should not expect it to compile with Node Sass.
