### ISSUE TITLE
Variable using is broken

### ISSUE THREAD

**Issue by dangreen** [sass/node-sass#1475]
Valid sass:
```
.landing__section--#{"[var__=guid__var]"}
        background-image: url(#{"[var__=background.value.image.value__var]"})
        background-position: #{5}% #{5}%
        background-size: #{"[var__=background.value.image.image.texture__var]"}

        &::before
                background-color: #{"[var__=overlayColor.value__var]"}
```

but in new version this code doesn't compile, but this
```
.landing__section--#{"[var__=guid__var]"}
        background-image: url(#{"[var__=background.value.image.value__var]"})
        background-position: #{5}% 5%
        background-size: #{"[var__=background.value.image.image.texture__var]"}

        &::before
                background-color: #{"[var__=overlayColor.value__var]"}
```

compiles without error

**Comment by mgreter** [comment]
Please try your code with ruby sass, I get an error on http://www.sassmeister.com/ for what you claim "valid sass". But maybe i'm not understanding your issue right.

**Comment by xzyfer** [comment]
Your first example does not compile with either Sass compiler or node-sass

```
Error: Invalid CSS after "#{5}% #{5}%": expected expression (e.g. 1px, bold), was ""
        on line 3 of test.sass
  Use --trace for backtrace.
```

Your second example produces the same output in both compilers, but the Sass compiler produces a deprecation warning
```
DEPRECATION WARNING on line 3 of test.sass: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote("5% 5%")

You can use the sass-convert command to automatically fix most cases.
```

**Comment by dangreen** [comment]
prints error:
```
.landing__section
    background-position: #{"5"}% #{"5"}%
```

doesn't print error:
```
.landing__section
    background-position: #{"5"}% 5%
```

**Comment by xzyfer** [comment]
@dangreen I understand. However it prints an error because the offical Sass compiler prints an error.

This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass
