### ISSUE TITLE
Naming convention documentation

### ISSUE THREAD

**Issue by slavede** [sass/node-sass#1576]
I'm trying to figure out the naming convention of the files and everything makes sense to me except last two numbers:

linux-x64-**47**_binding.node
linux-x64-**48**_binding.node

I used sass-binary-site where I first had only 47 and my Jenkins was pulling 47 version, but all of the sudden it decided it needs 48.

Can you document what are these numbers?

**Comment by xzyfer** [comment]
We do not document the binary names because they're not a public API. These names can change at any time.

The number you're referring to is the module version. It's tied to the version of the v8 API being used by node. This is important because our native binary is only valid for the version of node it was compiled against. This number changes the version of v8 used by node significanly changes. This usually happens on major versions of Node.

You can see your module version with 

```
node -p process.versions.modules
```

**Comment by slavede** [comment]
Just a question.

You said:

"These names can change at any time"

If I don't update node/npm on my machine, this should not happen? Because as I said, I didn't change anything and sass-binary tried to use different module version...

**Comment by xzyfer** [comment]
That number is tied to the version of node that is running npm install. If
you're system has changed from needing 47 to 48 it means node on that
machine was updated from node 5 to 6.

My comment was referring to the structure of the filename. It may change in
a future release of node-sass.

**Comment by slavede** [comment]
Cool, thanks for the info! 

So my initial question/idea is to comment what you just said to me to the wiki :)

**Comment by xzyfer** [comment]
For example our Linux binary isn't compatible for all Linux distributions.
In the future we may target specific distributions rather than having a
single generic Linux binary.

**Comment by xzyfer** [comment]
Unfortunately if we document it then it becomes a public API that needs to
be versioned. We'd prefer not to do this so that we're free to change the
format as we need in the future. Instead we're incrementally improving the
install process to give more meaningful errors that include information
about the Node versions they've previously used to install node-sass.

**Comment by slavede** [comment]
OK, cool, I understand. Thanks for explanation.
