### ISSUE TITLE
Assigning variables in @if statement

### ISSUE THREAD

**Issue by tomoakley** [sass/node-sass#1623]
I have just updated node-sass from v3.4.2 to v3.8.0, and some errors are appearing where I have used `@if` statements. Here is the Sass I have written:

```
$variable: value;
@if ($variable == 'value') {
  $padding: 2px;
} @else {
  $padding: 4px;
}

.selector {
  padding: $padding;
}
```

In node-sass v3.4.2 this worked perfectly, however I now get an `Undefined variable: $padding` error. Taken a look at the changelogs for node-sass and Libsass and couldn't find any notes about it (entirely possible I missed something though).

I appreciate this may not be an error with node-sass but it'd be great if someone could point me in the right direction. Thanks!

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by xzyfer** [comment]
I understand this feels like an unexpected breaking change. I've explained further in #1474.
