### ISSUE TITLE
Nested @font-face results in invalid syntax

### ISSUE THREAD

**Issue by mk1990** [sass/node-sass#1715]
Hi,
I encountered same problem with node-sass which appeared in sass before: https://github.com/sass/sass/issues/1251

The bug appears when @font-face is nested somewhere instead of being in root, for example:

```
#some-id {
  @font-face {
    font-family: ....;
    ....
  }
}
```

will be rendered as:
```
@font-face {
  #some-id {
    font-family: ....;
    ....
  }
}
```

I known I could put it in the root, but the problem is in this, it is vendor code (which declares both classes and @font-faces) and I am importing it in mine and it has to be applied only to underling #some-id element:

```
#some-id {
  @import "path/vendor";
}
```
so I was expecting that classes will be nested, but font-face will be added to root

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that Node Sass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by xzyfer** [comment]
https://github.com/sass/sass/issues/1251 was closed but no resolved to work as you wish as explained in https://github.com/sass/sass/issues/1251#issuecomment-44684317

**Comment by gluons** [comment]
Oh! I also face this problem. Sometime I have to import external CSS but they have `@font-face` inside. So, I can't use `@at-root`.

**Comment by rdsedmundo** [comment]
Same here. I'm trying to import an external module that uses `@font-face`.
