### ISSUE TITLE
Compiling errors while editing files remotely with watch mode.

### ISSUE THREAD

**Issue by dimamedia** [sass/node-sass#1788]
While editing large scss files remotely and uploading to the server. Watch mode detects changed files and start compiling while the files are still uploading. This cause compiling errors every time because of unfinished files.
On the extremely fast connections files are uploaded completely before compiler starts. But on slow connections there is no luck at all. Files have to be compiled every time manually.

The solution to this problem is to add a delay parameter with the seconds like `--delay 2`.

`node-sass -w scss -o css --delay 2 --output-style compact`

So there will be 2 second delay between change detection and compiling.

**Comment by Tes3awy** [comment]
Thanks a lot for the solutions. I googled a lot and opened previous issues, but their answers didn't help. Thanks to you, everything is working like a charm 👍.

But this appear to be happening with VSCode only. I tried with Atom & Sublime 3, but I don't get this error. But unfortunately, VSCode is my favorite 😄.

**Comment by MWGriffin** [comment]
I'm having the same issue with **VS Code** due to the fact that it doesn't have atomic writing capabilities. node-sass will detect a change before the file is completely written and will throw an error. This seems to happen about 40% of the time, and isn't a deal breaker but is fairly annoying. Adding a delay parameter like this would solve the issue as it would allow the file to be completely written.

**Comment by marcosbozzani** [comment]
The problem seems to be VSCode is still holding the file while node-sass try to access it. 

I've created a temporary workaround, that worked for me:
https://github.com/sass/node-sass/pull/2386

If you want to try it now, as a temporary measure, you can patch your node-sass local copy by replacing 'node_modules/node-sass/lib/render.js' with this version: https://github.com/marcosbozzani/node-sass/blob/bug-vscode-watch/lib/render.js

The diff is here: https://github.com/marcosbozzani/node-sass/commit/266861bf5761dcafd5d53d123264b965c861887c#diff-a485abf5b8f49de7f313d7799df3faf4

Hope it helps. :wink:

**Comment by saper** [comment]
Similar to #1615
