### ISSUE TITLE
Compilation loop when outputs in the same directory

### ISSUE THREAD

**Issue by milenon** [sass/node-sass#1845]
Hi, 

I'm starting node-sass from terminal with the following options:

`> node-sass -w -r ./ -o ./`

The problem is that when it compiles the changed .scss file and outputs it in the same folder it detects that the output .css file is changed and starts the compilation again and starts looping:

> => changed: D:\_\my-project\css\login.component.scss
> Rendering Complete, saving .css file...
> Wrote CSS to D:\_\my-project\css\login.component.css
> => changed: D:\_\my-project\css\login.component.css
> Rendering Complete, saving .css file...
> Wrote CSS to D:\_\my-project\css\login.component.css
> => changed: D:\_\my-project\css\login.component.css
> Rendering Complete, saving .css file...
> Wrote CSS to D:\_\my-project\css\login.component.css
> => changed: D:\_\my-project\css\login.component.css
> Rendering Complete, saving .css file...
> Wrote CSS to D:\_\my-project\css\login.component.css
> => changed: D:\_\my-project\css\login.component.css
> Rendering Complete, saving .css file...
> Wrote CSS to D:\_\my-project\css\login.component.css
> ...

Here are the environment details:

```
>node -p "require('node-sass').info"
node-sass       4.1.1   (Wrapper)       [JavaScript]
libsass         3.4.0   (Sass Compiler) [C/C++]
>npm -v
4.0.2
>node -v
v7.0.0
```

There were no such issues in version 3.11.2.

**Comment by xzyfer** [comment]
This is unfortunately expected behaviour. 

LibSass allows `.css` to be `@import`ed. This is bug but changing the behaviour would be a significant breaking change. As a result our watcher needs to watch for changes `.css` because they may be in the import graph.

LibSass will be fixing this bug in their 4.0 release. They must put it off until then because 4.0 will also introduce an offical way to import `.css` files so there is a way to keep the broken behaviour people are depending on.

For now the work around is to have different input and output directories.
