### ISSUE TITLE
`--precision` effect on darken - unclear if intentional or bug

### ISSUE THREAD

**Issue by birdspider** [sass/node-sass#1975]
is this excpected behaviour ?  #e6e6e6 vs.  #e6e5e5;

test.scss

```
a { color: darken(#fff,10%); }
```

compile

```
~ $ node-sass -v
node-sass       4.5.0   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

~ $ node-sass test.scss
a {
  color: #e6e6e6; }

~ $ node-sass --precision=8 test.scss
a {
  color: #e6e5e5; }
```

---

```
~ $ npm -v
4.6.1
~ $ node -v
v7.10.0
```
EDIT: node-sass 4.5.3 - same behaviour
XREF: https://github.com/sass/libsass/issues/2294

**Comment by mgreter** [comment]
I closed the upstream bug due to insignificant rounding errors. IMO nobody can really tell/see a difference between #e6e6e6 vs. #e6e5e5. Only real culprit I see is when you want to do a textual diff. Otherwise both colors are pretty much the same and just different due to rounding errors between 0.5 +- a tiny bit.
