### ISSUE TITLE
Npm rebuild node-sass error

### ISSUE THREAD

**Issue by maketroli** [sass/node-sass#2032]
When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 2.15.11

- Node version (`node -v`): 4.8.3

- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '4.8.3',
  v8: '4.5.103.47',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2k' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
/Users/Marcelo/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /Users/Marcelo/node_modules/node-sass/vendor/darwin-x64-46/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 4.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/Marcelo/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/Marcelo/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
```
When I run the command above(`npm rebuild node-sass --force`), I get this error: `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

- npm node-sass versions (`npm ls node-sass`):

```
└─┬ grunt-sass@0.18.1
  └── node-sass@2.1.1 
```

I am using nvm: 0.33.2

Any suggestions?

**Comment by xzyfer** [comment]
Whenever you change node versions you'll need to remove your node_modules
and npm install

**Comment by maketroli** [comment]
@xzyfer that is implicit.
The error still there, mate.

**Comment by xzyfer** [comment]
There is a lot going on here.

>node-sass@2.1.1

This ancient, and will not install properly anymore. It's also not the version of node-sass supplying the error you're seeing because it was added in node-sass@3.

>that is implicit.

Nothing is implicit when you're asking for help.

```
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 4.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x
```

The error message appears to contradict you have followed my initial instructions. Node Sass was installed under Node 8 successfully. You've since changed to Node 6. The node_modules folder wasn't removed because node-sass can still see the successful installation under Node 8. 

Since you're using nvm make sure all your tabs are on the same version.

>xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory

The forced rebuild requires Xcode installed on OSX. However since we're able to determine you're on Node 6 a forced rebuild isn't necessary. We should make these instructions more clear.

>, mate.

Be nice please, we don't have to help. I could happily be enjoying my dinner.

**Comment by guanpu** [comment]
I am sorry to bother, just walk by, but is 'mate' a word meaning something non-respectful?
