### ISSUE TITLE
stops running if wrong css entered

### ISSUE THREAD

**Issue by bhvreddy** [sass/node-sass#2055]
- NPM version (`npm -v`):  5.3.0
- Node version (`node -v`): 8.2.1
- Node Process (`node -p process.versions`):  
{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):

---

node-sass stops if an error found in css 

i am using vs code, and try to run node-sass to compile .scss file to .css file 

what i tried 

`node-sass scss/main.scss assets/css/main.css --quiet --watch
`
error

``` 
/npm/node-sass: line 14:  3472 Segmentation fault      node "$basedir/node_modules/node-sass/b
in/node-sass" "$@"
```

```
{
  "status": 3,
  "message": "File to read not found or unreadable: D:/MAMP/htdocs/wp/wp-content/themes/re/scss/main.scss",
  "formatted": "Internal Error: File to read not found or unreadable: D:/MAMP/htdocs/wp/wp-content/themes/re/scss/main.scss\n"
}
```

**Comment by RoyTinker** [comment]
node-sass-chokidar is a pretty good workaround for this.

**Comment by xzyfer** [comment]
This is interesting.

```
File to read not found or unreadable: D:/MAMP/htdocs/wp/wp-content/themes/re/scss/main.scss
```

Suggests the scss file doesn't exists at the location you've supplied.

```
/npm/node-sass: line 14:  3472 Segmentation fault      node "$basedir/node_modules/node-sass/b
in/node-sass" "$@"`
```

Suggests something in the file is invalid and causing LibSass (the engine node-sass uses) to crash. This may be what's causing node-sass to thing the file doesn't exists, or LibSass could be crashing because the file doesn't exist.

Can you please
- confirm `D:/MAMP/htdocs/wp/wp-content/themes/re/scss/main.scss` exists at that location
- if so, please create a gist.github.com with the file contents so we can see why it's crashing LibSass
