### ISSUE TITLE
Sass-graph CSS parse bug (against css files) causes process termination in --watch mode only

### ISSUE THREAD

**Issue by RoyTinker** [sass/node-sass#2185]
**Reduced test case (git repo):**
https://github.com/RoyTinker/node-sass-watch-import-css-bug
(see README.md there for repro instructions)

There seem to be 2 problems here:
- node-sass's watcher uses sass-graph with `'css'` configured as an extension to parse (note: css files are _not_ parsed when compiling via node-sass in non-watch mode)
- sass-graph seems to have a bug when parsing certain CSS imports.

I suspect the solution would involve the following:
- fix config options when calling sass-graph from the watcher to _not_ parse CSS files
- file a bug on sass-graph for the parsing bug

**Info:**
- NPM version: `5.6.0`
- Node version: `v9.2.1`
- Node Process:
```
{ http_parser: '2.7.0',
  node: '9.2.1',
  v8: '6.2.414.44-node.11',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node platform: `darwin`
- Node architecture: `x64`
- node-sass version:
```
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions:
```
node-sass-watch-import-css-bug@0.0.1 /Users/roy4662/projects/node-sass-watch-import-css-bug
└── node-sass@4.7.2
```

**Comment by xzyfer** [comment]
Imported CSS are always parses by node sass. This is due to a feature/bug
in LibSass. As a result we must parse CSS files with sass graph.

Regarding sass graph bugs. Please open an issue in their issue tracker.

On 13 Dec. 2017 9:09 am, "Roy Tinker" <notifications@github.com> wrote:

*Reduced test case (git repo):*
https://github.com/RoyTinker/node-sass-watch-import-css-bug
(see README.md there for repro instructions)

There seem to be 2 problems here:

   - node-sass's watcher uses sass-graph with 'css' configured as an
   extension to parse (note: css files are *not* parsed when compiling via
   node-sass in non-watch mode)
   - sass-graph seems to have a bug when parsing certain CSS imports.

I suspect the solution would involve the following:

   - fix config options when calling sass-graph from the watcher to *not*
   parse CSS files
   - file a bug on sass-graph for the parsing bug

*Info:*

   - NPM version: 5.6.0
   - Node version: v9.2.1
   - Node Process:

{ http_parser: '2.7.0',
  node: '9.2.1',
  v8: '6.2.414.44-node.11',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }


   - Node platform: darwin
   - Node architecture: x64
   - node-sass version:

node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]


   - npm node-sass versions:

node-sass-watch-import-css-bug@0.0.1
/Users/roy4662/projects/node-sass-watch-import-css-bug
└── node-sass@4.7.2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/2185>, or mute the thread

**Comment by RoyTinker** [comment]
@xzyfer:
- The CSS file is not imported from anything.
- It is not parsed when running node-sass without `--watch`
