### ISSUE TITLE
4.6.0 to 4.7.2 are missing Windows binaries for Node < 4

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#2222]
This was intentionally dropped in https://github.com/sass/node-sass/commit/e934a55d5a0433e8e1d483a485c4717c9a416b6c#diff-180360612c6b8c4ed830919bbb4dd459
@xzyfer should we update the release notes to indicate the support on Windows has changed or add those platforms back and generate the bindings

**Comment by xzyfer** [comment]
We should probably regenerate the binaries. Some of those releases are actually bugfixes for broken Node < 4 support so we only need to build binaries for a couple releases - 4.6.1, 4.7.0, 4.7.2

**Comment by saper** [comment]
Maybe we can use this opportunity to fix CentOS 5 for node < 8 and make a new release out of that.

**Comment by xzyfer** [comment]
Yep we prematurely removed Node < 4 from CI scripts expecting to not cut
any more 4.x releases. This has bitten us a couple times by breaking BC in
releases, and not building windows binaries. For now I think we should add
these old versions backs to CI scripts, and rebuild the broken windows
binaries for Node < 8 support.

On 29 Jan. 2018 6:16 am, "Marcin Cieślak" <notifications@github.com> wrote:

Maybe we can use this opportunity to fix CentOS 5 for node < 8 and make a
new release out of that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/2222#issuecomment-361087778>, or mute
the thread

**Comment by isochronous** [comment]
Yes, please do this sooner rather than later.  I've had to deal with half a dozen issues stemming from these missing binaries over the past week.

**Comment by nschonni** [comment]
@saper will that script you use help pull the binaries from https://ci.appveyor.com/project/nschonni/node-sass/build/97 or should I just manually copy them over?

**Comment by nschonni** [comment]
Looks like https://github.com/nodejs/nan/issues/725 was causing the IO.js 3 builds to fail. There is a fix landed now and I retriggered the build

**Comment by saper** [comment]
Appveyor script will upload if tagged release is detected... (Tricky sometimes)

**Comment by saper** [comment]
yes, I didn't have a script but that does not mean I could not write one :) The binaries are attached to the 4.7.2 release, would be good to test them.

**Comment by xzyfer** [comment]
I have a script to copy binaries from one release to another that support
regexp filtering. It's how I do releases on Australian internet 😂

**Comment by saper** [comment]
Yep I have a couple of GitHub release upload/download scripts but I needed to write an @AppVeyor one since I don't have PowerShell :) Basically it iterates all jobs of the latest build and downloads all artifacts.
