### ISSUE TITLE
Globs not working in node-sass with npm script

### ISSUE THREAD

**Issue by ochstobi** [sass/node-sass#2225]
- NPM version: 5.6.0
- Node version: 9.4.0
- Node Process: { http_parser: '2.7.0',
  node: '9.4.0',
  v8: '6.2.414.46-node.17',
  uv: '1.18.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform: win32
- Node architecture: x64
- node-sass version: 
node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions: 4.7.2

I try to compile some scss files in a folder (but not every file). My idea was this:
`"build-task:scss-compile": "node-sass src/assets/scss/myfile-*.scss -o dist/css"`
But i get "No input file was found." error.
I also tried to move the other files in a sub directory, but node-sass always compiles subfolders, too.

**Comment by xzyfer** [comment]
The node-sass click either compiled a single input file to a single outout file, or single input directory to single output directory.

**Comment by eps1lon** [comment]
Just to clarify this:
The input argument currently does not support glob patterns. It relies on the shell to expand those glob patterns:

```
$ node_modules/.bin/node-sass "themes/*.scss" -o themes
No input file was found.
$ node_modules/.bin/node-sass themes/*.scss -o themes
Rendering Complete, saving .css file...
Wrote CSS to c:\Development\src\js\poe\components\item\themes\poe.css
```
@xzyfer 
Since `glob` is already listed in the dependencies could we get an option to explicitly provide a glob pattern?

Otherwise running `node-sass themes/*.scss -o themes` from a npm script on windows is equivalent to `node_modules/.bin/node-sass "themes/*.scss" -o themes` which results in no input found.

**Comment by zivc** [comment]
Not sure if this is the same issue but,

```node-sass ./src/**/*.scss -o ./build/src/```

Doesn't compile `./src/file.scss`

However the following does,

```node-sass ./**/*.scss -o ./build/src/```
