### ISSUE TITLE
node-sass 4.7.2 installation error - npm - Mac OS X High Sierra

### ISSUE THREAD

**Issue by rik72** [sass/node-sass#2263]
It seems that I cannot install node-sass in my environment. I'm on Mac OS X 10.13.3.
To replicate, I simply execute:

```
mypath root# npm install node-sass
```
as root.

Detailed log follows:

```
> node-sass@4.7.2 install /mypath/node_modules/node-sass
> node scripts/install.js

Unable to save binary /mypath/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/mypath/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/mypath/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/mypath/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/mypath/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/mypath/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/mypath/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /mypath/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /mypath/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/mypath/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /mypath/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/mypath/node_modules/node-sass/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/mypath/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /mypath/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

- NPM version: 5.6.0
- Node version: v8.9.4
- Node Process: { http_parser: '2.7.0',  node: '8.9.4',  v8: '6.1.534.50',  uv: '1.15.0',  zlib: '1.2.11',  ares: '1.10.1-DEV',  modules: '57',  nghttp2: '1.25.0',  openssl: '1.0.2n',  icu: '59.1',  unicode: '9.0',  cldr: '31.0.1',  tz: '2017b' }
- Node Platform: darwin
- Node architecture: x64
- node-sass version: n.a.
- npm node-sass versions: n.a.

**Comment by xzyfer** [comment]
The error message clearly indicates this is a permission issue trying to
create '/mypath/node_modules/node-sass/vendor'.

Npm runs scripts as a restricted user, no root.

You can try using the --unsafe-perms flag to npm install. Otherwise you
need to fix your permissions.

On 2 Mar. 2018 12:38 am, "rik72" <notifications@github.com> wrote:

It seems that I cannot install node-sass in my environment. I'm on Mac OS X
10.13.3.
To replicate, I simply execute:

mypath root# npm install node-sass

as root.

Detailed log follows:

> node-sass@4.7.2 install /mypath/node_modules/node-sass
> node scripts/install.js

Unable to save binary
/mypath/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES:
permission denied, mkdir '/mypath/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/mypath/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/mypath/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary
(/mypath/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous>
(/mypath/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/mypath/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /mypath/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node
/mypath/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose
--libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/mypath/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import
platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to
host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir:
/mypath/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir
'/mypath/node_modules/node-sass/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node"
"/mypath/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose"
"--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd /mypath/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.


   - NPM version: 5.6.0
   - Node version: v8.9.4
   - Node Process: { http_parser: '2.7.0', node: '8.9.4', v8: '6.1.534.50',
   uv: '1.15.0', zlib: '1.2.11', ares: '1.10.1-DEV', modules: '57', nghttp2:
   '1.25.0', openssl: '1.0.2n', icu: '59.1', unicode: '9.0', cldr: '31.0.1',
   tz: '2017b' }
   - Node Platform: darwin
   - Node architecture: x64
   - node-sass version: n.a.
   - npm node-sass versions: n.a.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/2263>, or mute the thread

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs

**Comment by rik72** [comment]
Thank you.

**Comment by cbernard** [comment]
Hello,

I'm having the same issue and I tried the previous link but still nothing changed.

Any other recommandations ?

Thank you.

**Comment by xzyfer** [comment]
Please open a new issue

**Comment by stevematdavies** [comment]
Same issue three weeks later, no solution

**Comment by xzyfer** [comment]
The issue resolution was very clear. The OP didn't have the right permissions to install a global package.

Use the suggested resolution or open a new issue.

**Comment by lek-tin** [comment]
try:
`sudo rm -rf node_modules && npm rebuild node-sass && npm i`
ref: http://froshgeek.com/fix-npm-error-permission-denied-mkdir-related-to-node-sass-macos/
