### ISSUE TITLE
Node Sass does not yet support your current environment (Mac OS Mojave)

### ISSUE THREAD

**Issue by cavico** [sass/node-sass#2432]
Node Sass does not yet support your current environment
Mac OS 10.14 Beta (18A314k)

- NPM version 6.1.0
- Node version v9.8.0
- Node Process { http_parser: '2.7.0',
  node: '9.8.0',
  v8: '6.2.414.46-node.21',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '2',
  openssl: '1.0.2n',
  icu: '60.2',
  unicode: '10.0',
  cldr: '32.0.1',
  tz: '2017c' }
- Node Platform darwin
- Node architecture x64
- npm node-sass versions node-sass@3.13.1 > gulp-sass@2.3.2

Can you help me? Thanks

**Comment by xzyfer** [comment]
That's version of node-sass is too old to work on node 8. Run npm update
node-sass.

**Comment by cavico** [comment]
@xzyfer i've tried that, but now I have this error:
Error: Missing binding /node_modules/node-sass/vendor/darwin-x64-59/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 9.x

Could you help me? Thanks!

**Comment by xzyfer** [comment]
npm rebuild node-sass

**Comment by akmil** [comment]
Error...
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/darwin-x64-64_binding.node":

**Comment by charlenebuena** [comment]
npm rebuild node-sass didn't work for me because it says it wasn't able to see node-sass in node_modules. so I `npm install node-sass` and it worked

**Comment by hamzakalfa** [comment]
none of the solutions above have worked until I tried npm install node-sass and it worked well. thanks @charlenebuena

**Comment by fabiobarboza7** [comment]
To fix my problem I rebuild but it didn’t work after it I followed  what CharleneBuena said:

`nim install node-sass` and now [ok]

**Comment by cfsavant** [comment]
nothing works

**Comment by fabiobarboza7** [comment]
@cfsavant , can you print you error?

**Comment by xzyfer** [comment]
npm update node-sass

**Comment by jasonfb** [comment]
I ran into this problem after what I Think was caused by an X Code 10.1 -> 9.4 DOWNGRADE (I think that's what caused it). First I had some nasty problems with node-sass, then I blew away my `node_modules` and was then unable to `yarn install` again without serious problems.

then I got through that but got to
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
```

I was able to fix this by switching my system over from (what I think was) brew-installed `node`, which annoyingly is difficult to downgrade, to `nvm` (https://github.com/nvm-sh/nvm)

then, once I made sure I had the right node version, I was able to
`yarn cache clean`

and also `yarn install`

then I ran into a nasty rabbit hole with the dev environment only, which was simply fixed by restarting my system after which my app started booting in dev again.
