### ISSUE TITLE
Cache output and only overwrite files when output has changed

### ISSUE THREAD

**Issue by dgieselaar** [sass/node-sass#246]
Is it possible to only overwrite files if the output has actually changed? I'm running into issues with grunt-contrib-watch and livereload (all files are overwritten, even if the content hasn't changed, and grunt-contrib-watch passes all files to livereload which results in performance problems).

**Comment by cuth** [comment]
I'd like to request that this feature be considered again.

The reason for closing this feature is that *"it's meant to be a wrapper around libsass"*. But it is more than that because it also offers a CLI. Since the Ruby Sass CLI supports a cached output, I feel like the node-sass CLI is incomplete.

**Comment by xzyfer** [comment]
@cuth the Ruby Sass CLI doesn't support this as requested. It does one of two things -

- keeps an intermediary cached object for fast compilations
- when watching, only update files that are affected by a change

The former is done to speed up compilation times of files that haven't changed between compilations. Since Libsass is significantly faster than node-sass we don't require this.

The latter is implemented in out watcher. However libraries like grunt and gulp do not use our watcher so you need re-implement this _smart_ watching yourself when using these libraries. You can do with sass-graph.

A gulp implementation of this might look like https://gist.github.com/xzyfer/1225f52c370b511c1fed

**Comment by cuth** [comment]
"Since Libsass is significantly faster than node-sass we don't require this."

That makes sense. Thanks for the explanation!
