### ISSUE TITLE
Two days into trying to install this, I'm still getting this:

### ISSUE THREAD

**Issue by sabsaxo** [sass/node-sass#2533]
Can someone, please, explain to me what I have to do to get passed this? I've tried EVERYTHING, updating from El Capitan to High Sierra, updating Homebrew, reinstalling all thinkable node versions, all thinkable versions of node via nvm, the list is endless. What is it that I'm obviously totally missing?
```
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/MAMP/htdocs/wp-content/themes/mytheme/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/sam/.nvm/versions/node/v10.13.0/bin/node" "/Applications/MAMP/htdocs/wp-content/themes/mytheme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Applications/MAMP/htdocs/wp-content/themes/mytheme/node_modules/node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN base_build@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2018-11-01T12_16_41_637Z-debug.log

```
And no, the log doesn't make it any clearer.

**Comment by xzyfer** [comment]
The release notes state that node-sass@3.10.1 does not support Node 10 - https://github.com/sass/node-sass/releases/v3.13.1

>And no, the log doesn't make it any clearer

The issue template clearly outlines the information we need in order to help. By ignoring the template, and not uploading the log there is nothing we can do besides direct you at the [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md).

Try the steps outline here to rule out weird environment issues: https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx

If none of the helps open a new issue and follow the issue template.
