### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-79_binding.node"

### ISSUE THREAD

**Issue by Mustafa-Hayati** [sass/node-sass#2773]
Hi I'm trying to make the webpack.configure.js file work, and when I want to install sass-loader and node sass (according to the document I have to install both) using the npm install sass-loader node-sass --save-dev , it fails and throws error

- NPM version 6.10.2
- Node version 12.9.1:
- Node Process  {
  node: '12.9.1',
  v8: '7.6.303.29-node.15',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
- Node Platform win32
- Node architecture x64
- node-sass version -
- npm node-sass versions` -- (empty)

**Comment by nschonni** [comment]
Please provide the log, there is nothing we can troubleshoot here

**Comment by Mustafa-Hayati** [comment]
I can't upload the log file, it says, something went really wrong, and we can't process the file.

**Comment by FlyRocketDrones** [comment]
I have the same issue, here is the log file.
I did not encounter this issue yesterday when I did npm install. Today I deleted node modules and did npm install now I get this error.
[2019-10-24T14_22_45_888Z-debug.log](https://github.com/sass/node-sass/files/3768033/2019-10-24T14_22_45_888Z-debug.log)

**Comment by ramiel** [comment]
I have this error
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux_musl-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/linux_musl-x64-79_binding.node": 
```

**Comment by saper** [comment]
@ramiel Please see https://github.com/sass/node-sass/issues/2765#issuecomment-545915564

**Comment by Mustafa-Hayati** [comment]
I installed the new version of node and npm and it is still the same. 
https://gist.github.com/Mustafa-Hayati/0fbb5bbbc95aa2add18a4a8f5513eabf

**Comment by FlyRocketDrones** [comment]
v4.12 was fine. I believe it has to do with v4.13 of node-sass

**Comment by Mustafa-Hayati** [comment]
I tried v4.12 too, but it didn't work either

**Comment by FlyRocketDrones** [comment]
@Mustafa-Hayati you need to remove ^ in front of the version otherwise it'll keep trying to load 13.. make it like this `"node-sass": "4.12.0",`


@saper  I created a new project using create-react-app then attempted to add node-sass by npm i -g node-sass

here's error, also attached the log file.
A778765@145LFF5LQV2 MINGW64 /c/1
$ npm config set proxy http://proxy.admworld.com:80

A778765@145LFF5LQV2 MINGW64 /c/1
$ npm i -g node-sass
C:\Users\A778765\AppData\Roaming\npm\node-sass -> C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@4.13.0 install C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-64_binding.node":

Client network socket disconnected before secure TLS connection was established

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:68:19)\n
at E (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\A778765\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\A778765\AppData\Roaming\npm\node_modules\node-sass
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\A778765\AppData\Roaming\npm-cache\_logs\2019-10-24T18_25_13_373Z-debug.log
[2019-10-24T18_25_13_373Z-debug.log](https://github.com/sass/node-sass/files/3768936/2019-10-24T18_25_13_373Z-debug.log)

**Comment by saper** [comment]
@FlyRocketDrones This is a problem with your network proxy not allowing connections to Github and Amazon S3. There is nothing we can do here, worst case you can download the file from https://github.com/sass/node-sass/releases/tag/v4.13.0 and set environment variable `SASS_BINARY_PATH` to the full path of thie binding (please note it will not be copied though!)

Thank you for explaining @Mustafa-Hayati 's problem!

```

C:\Users\saper\Downloads>wget -q https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-64_binding.node

C:\Users\saper\Downloads>copy win32-x64-64_binding.node ..\safe_node_module
        1 file(s) copied.

C:\Users\saper\Downloads>set SASS_BINARY_PATH=C:\Users\saper\safe_node_module\win32-x64-64_binding.node

C:\Users\saper\Downloads>cd ..\ns10

C:\Users\saper\ns10>npm install node-sass

> node-sass@4.13.0 install C:\Users\saper\ns10\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at C:\Users\saper\safe_node_module\win32-x64-64_binding.node

> node-sass@4.13.0 postinstall C:\Users\saper\ns10\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\saper\safe_node_module\win32-x64-64_binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\saper\ns10\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\saper\ns10\package.json'
npm WARN ns10 No description
npm WARN ns10 No repository field.
npm WARN ns10 No README data
npm WARN ns10 No license field.

+ node-sass@4.13.0
added 174 packages from 138 contributors and audited 529 packages in 20.875s
found 0 vulnerabilities
```

**Comment by saper** [comment]
@Mustafa-Hayati can you paste few lines from npm output just like @FlyRocketDrones  did?

**Comment by Mustafa-Hayati** [comment]
> node-sass@4.13.0 install D:\Practice\webpack\Colt-youtube\my\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-79_binding.node":

connect ECONNREFUSED 127.0.0.1:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall D:\Practice\webpack\Colt-youtube\my\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\Practice\webpack\Colt-youtube\my\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.0.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Mustafa\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` failed Error: not found: C:\Users\Mustafa\.windows-build-tools\python27\python.exe
gyp verb `which` failed     at getNotFoundError (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  C:\Users\Mustafa\.windows-build-tools\python27\python.exe Error: not found: C:\Users\Mustafa\.windows-build-tools\python27\python.exe
gyp verb `which` failed     at getNotFoundError (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Practice\webpack\Colt-youtube\my\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: C:\\Users\\Mustafa\\.windows-build-tools\\python27\\python.exe\n' +
gyp verb `which` failed     '    at getNotFoundError (D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "C:\Users\Mustafa\.windows-build-tools\python27\python.exe". checking python launcher
gyp verb could not find "C:\Users\Mustafa\.windows-build-tools\python27\python.exe". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Mustafa\.windows-build-tools\python27\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Practice\webpack\Colt-youtube\my\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Practice\webpack\Colt-youtube\my\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (D:\Practice\webpack\Colt-youtube\my\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Practice\\webpack\\Colt-youtube\\my\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Practice\webpack\Colt-youtube\my\node_modules\node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!

**Comment by Mustafa-Hayati** [comment]
I don't have access to those two links up above

**Comment by saper** [comment]
Yes, you cannot connect to the proxy on localhost `127.0.0.1:443` you have configured.

**Comment by FlyRocketDrones** [comment]
@saper makes sense. So for anyone who's having this issue, it is caused by v4.13 hosted at a location that doesn't seem secure to our networks. So unless you find a way to get this version thru proxy, you'll have to stay at v4.12.

**Comment by nschonni** [comment]
It's the exact same release mechanism as 4.12 (GitHub releases, which is backed by S3)

**Comment by FlyRocketDrones** [comment]
npm install for v4.12 works, v4.13 doesn't. if it's azure connection issue, it would happen for v4.12 as well

**Comment by saper** [comment]
I don't know, maybe things for 4.12 got cached; maybe there are rules on the proxy that block any URL with "13", who knows... it's a connectivity issue.

**Comment by Mustafa-Hayati** [comment]
What if I download the whole node-sass zip file from github? will it work? where should i put it? what should I add to package.json? can you help me?

**Comment by xzyfer** [comment]
Update to node-sass@4.13

**Comment by Mustafa-Hayati** [comment]
@xzyfer It doesn't work not matter what. I updated node and npm and nothing worked. I don't have access to the postinstall links.

**Comment by Mustafa-Hayati** [comment]
@saper What if I download the whole node-sass zip file from github? will it work? where should i put it? what should I add to package.json? can you help me?

**Comment by saper** [comment]
@Mustafa-Hayati please check https://github.com/sass/node-sass/issues/2728 and the README file to determine the right module number for you. Download the file manually and follow the steps I have given in https://github.com/sass/node-sass/issues/2773#issuecomment-546049760 to use a downloaded file.

**Comment by AcidSlide** [comment]
For those who is having this issue, I think this is a windows issue.  I've been having trouble since middle of this year (around August or September 2019 I think) with HTTPS connections in the command line.  This has affected NPM installs and other scripts that need to get or call HTTPS connections.

I think is actually a windows issue.  This is one of reason I HATE using Windows as a development machine.
https://answers.microsoft.com/en-us/windows/forum/all/help-getting-https-to-work-in-command-line-in/6d226e12-f76b-47f8-8dac-1060f3047a08

FYI: I don't have a network proxy or any kind of proxy setup in my network or my computers.

**Comment by saper** [comment]
Thanks, this is great. This could be also registry issue... Anything in the npm communities?

**Comment by saper** [comment]
@AcidSlide do you have a possibility to sniff the failing traffic with for example Wireshark and post it somewhere as a binary file?

**Comment by AcidSlide** [comment]
@saper I'll try to sniff it, hopefully before switch back to mac.. i'm only using the windows machine until this week

By the way, for those having this issue, I have a temporary workaround, to get things working in Windows which is very similar to what @saper  mentioned in [#2773 (comment)](https://github.com/sass/node-sass/issues/2773#issuecomment-546049760) but instead of setting it in PATH, directly download the file into the correct folder for the installation to continue.

Although to be honest, saper's method si simplier.

**Comment by miguelangcosta** [comment]
This started to give error when I uopgraded to Cataline in MAC

I solved with:
run node-sass uninstall and then
sudo npm install --unsafe-perm -g node-sass

**Comment by davidgarvie** [comment]
For anyone else struggling with this issue I received a similar error message when working on OSX after upgrading my version of npm. Try removing your project's local `package-lock` file and rerun `npm install` to see if it resolves the error.

**Comment by juanlet** [comment]
I'm getting this same error in OS x after updating to Catalina....

**Comment by LucasOta** [comment]
For those that are using Windows, first you have to install  the last version of phyton and the the "Windows build tools" with the following command (on an an elevated PowerShell or CMD.exe (run as Administrator) 

npm install --global --production windows-build-tools

Then run "npm i" or "npm install node-sass" on your project.

This worked for me.
Hope it helps.

**Comment by anavulla** [comment]
407 means proxy authentication is failing, add username and password to proxy settings: 
Note: Don't forget to include single quotes around username/password if you have special chars.

npm config set proxy "http://'**myusername**':'**mypassword**'@myproxy.com:3128/"
npm config set https-proxy "http://'**myusername**':'**mypassword**'@myproxy.com:3128/"
npm config set unsafe-perm=true
npm config set strict-ssl false

**Comment by josephdicdican** [comment]
@LucasOta thanks for this, it did fix the issue.

Ionic@5.4.13
Used powershell as administrator.

```bash
> npm install --global --production windows-build-tools # long process around 3-5 mins
> npm install # there were couple of warnings but I just ignored them
> npm run ionic:serve # script from package.json "ionic:serve": "ionic-app-scripts serve"
> ionic-hello-world@ ionic:serve C:\Users\**\Sites\bitbucket\**-ionic-app
> ionic-app-scripts serve

[16:45:59]  ionic-app-scripts 2.0.2 
[16:45:59]  watch started ... 
[16:45:59]  build dev started ... 
[16:45:59]  clean started ... 
[16:45:59]  clean finished in 7 ms 
[16:45:59]  copy started ... 
[16:45:59]  transpile started ... 
[16:46:06]  transpile finished in 6.72 s 
[16:46:06]  preprocess started ... 
[16:46:06]  deeplinks started ... 
[16:46:06]  deeplinks finished in 291 ms 
[16:46:06]  preprocess finished in 292 ms 
[16:46:06]  webpack started ... 
[16:46:07]  copy finished in 7.38 s 
[16:46:14]  webpack finished in 7.65 s 
[16:46:14]  sass started ... 
[16:46:18]  sass finished in 3.64 s 
[16:46:18]  postprocess started ... 
[16:46:18]  postprocess finished in 8 ms 
[16:46:18]  lint started ... 
[16:46:18]  build dev finished in 18.72 s 
[16:46:18]  watch ready in 19.16 s 
[16:46:18]  dev server running: http://localhost:8100/ 
```

**Comment by divyanipatil** [comment]
I'm facing a similar problem but it's trying to download the binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node which doesn't exist. I checked the list at https://github.com/sass/node-sass/releases/.
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node": 

HTTP error 404 Not Found
```

 Version for node-sass as per package-lock.json is 4.11 but I don't understand why it's looking for linux-x64-**79**_binding.node! Can someone please help me understand how I can fix this, any pointers?

Thanks!
