### ISSUE TITLE
sass-graph should be updated to version 3

### ISSUE THREAD

**Issue by stof** [sass/node-sass#2863]
node-sass currently depends on sass-graph 2.2.4. This version depends on a version of yargs which gets reported as a security vulnerability by Snyk.
It would be great to update to the maintained version of sass-graph rather than using this old version.

**Comment by xzyfer** [comment]
This will happen in v5

**Comment by stof** [comment]
is there any estimate for when v5 will be ready ? It seems to be in progress since at least 2 years.

**Comment by raparlasiva** [comment]
We have a similar issue on our veracode scan. It would really help us if you can provide an estimate on when v5 is in teh pipeline

**Comment by xzyfer** [comment]
If this is really an issue for your CI environment I recommend opening a PR against the sass-graph v2 branch (https://github.com/xzyfer/sass-graph/tree/v2) to bump the vulnerable dependencies.

**Comment by stof** [comment]
hmm, due to node-sass needing to support old node.js versions in its v4 version, upgrading yargs in sass-graph v2 won't work. Yargs 8 requires Node 4+ and yargs 12 requires Node 6+, while getting a version in which the vulnerability is patched requires upgrading at least to yargs 13.
So we won't be able to get the fix until node-sass v5.

**Comment by henry-chris** [comment]
Just making sure I understand what @stof is getting at.  Since the same security vulnerability is being reported by a bunch of different scans.

These vulnerabilities do not exist in the files/code generated by node-sass right?  For instance, the CSS which is output from the pre-processing?  I can't see how it would. 

It should only be a security hole if you are actively running this package somewhere, right?

I guess running build steps in the cloud is where it could happen?

**Comment by nschonni** [comment]
Separate from the v3 upgrade, but #2915 will have a patch for yargs only

**Comment by xzyfer** [comment]
Fixed in v4.14.1
