### ISSUE TITLE
mkdirp 0.0.8 vulnerability

### ISSUE THREAD

**Issue by YellowPanda11** [sass/node-sass#2876]
The version of mkdirp the latest release is relying on has a security vulnerability.
https://snyk.io/test/npm/minimist/0.0.8

It needs to be on 0.5.2 at least per the suggestion above.

**Comment by nschonni** [comment]
It already will install that with the `^` https://github.com/sass/node-sass/blob/b54053a1b50fd97e951eb0311a7fb818683a8e99/package.json#L65
Clear your package-lock.json and re-install if it's stuck on your local install

**Comment by thatguyjono94** [comment]
@nschonni I've got `"node-sass": "^4.13.1"`, after deleting package.json and node modules and running `npm install` I still don't get an updated mkdirp version?

**Comment by augnustin** [comment]
:+1: here

I don't see how this can be fixed since, as @nschonni mentionned, node-sass requires `mkdirp: ^0.5.1` and @YellowPanda11 said that `0.5.2+` is required.

Also removing `package-lock.json`, besides not working, is not an acceptable solution as it can have many other unexpected side-effects.

This is really an issue to me.

**Comment by nschonni** [comment]
Here is a package-lock.json with just node-sass install https://gist.github.com/nschonni/ac56f3a80f3e402e3e68c2299f186c69
There are no vulnerable versions, and there is nothing a new version would fix for your issues.
You likely have other packages requiring older mkirp versions.

Locking this issue
