### ISSUE TITLE
VS CODE with ESLINT & Prettier Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (75)

### ISSUE THREAD

**Issue by ErSulba** [sass/node-sass#2962]
Eslint and Prettier for VSCode cannot launch because of `Cannot read config file: /Users/alejandro.sulbaran/projects/my-ui/.eslintrc.js Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (75)` i've tried `npm rebuild node-sass --force` and deleting and reinstalling node-sass from project itself but none of that works, funny thing is that i can run ESLINT and Prettier from the terminal, but otherwise node-sass keeps complaining on VSCODE with every tool that use prettier or eslint.

- NPM version (`npm -v`):6.14.6
- Node version (`node -v`):12.8.3
- Node Process (`node -p process.versions`): 
```
{
	  node: '12.18.3',
	  v8: '7.8.279.23-node.39',
	  uv: '1.38.0',
	  zlib: '1.2.11',
	  brotli: '1.0.7',
	  ares: '1.16.0',
	  modules: '72',
	  nghttp2: '1.41.0',
	  napi: '6',
	  llhttp: '2.0.4',
	  http_parser: '2.9.3',
	  openssl: '1.1.1g',
	  cldr: '37.0',
	  icu: '67.1',
	  tz: '2019c',
	  unicode: '13.0'
	}
```

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
	```
	node-sass	4.14.1	(Wrapper)	[JavaScript]
	libsass  	3.5.5	(Sass Compiler)	[C/C++]
	```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.14.1

**Comment by nschonni** [comment]
node-sass should have no interaction with ESLint or Prettier. node-sass doesn't support being run in in Electron (VS Code) versions of node, so we can't help troubleshoot. The "75" indicates this is something running inside an Electron rather than Node environment https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support
