### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node"

### ISSUE THREAD

**Issue by Marietto2008** [sass/node-sass#3141]
Hello to everyone. I would like to install ferdi inside docker on my jetson nano (arm64). Below u can see what I did right now. Unfortunately there is an error I'm not able to fix. 

```
FROM ubuntu:hirsute
LABEL Title="arm64/ferdi"

# Enviorment variables

ARG username=mario
ENV HOME /home/$blenderartistusername
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV PATH "/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib:/usr/include:/usr/share"
ENV HW="GPU"
ENV ELECTRON_CACHE /home/$username/.cache/electron
ENV ELECTRON_BUILDER_CACHE /home/$username/.cache/electron-builder
ENV TERM xterm

RUN mkdir /home/$username

#RUN apt-get update && apt-get install -y build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libgnome-keyring-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python-dbusmock openjdk-8-jre libc6-dev-arm64-cross linux-libc-dev-arm64-cross g++-aarch64-linux-gnu

RUN apt-get update && apt-get install -y ca-certificates curl netbase wget tzdata rpm git xz-utils nano gedit

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get install -y nodejs gcc g++ make

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null

RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install yarn

RUN git clone https://github.com/getferdi/ferdi.git && cd ferdi && git submodule update --init --recursive

# Note: This is being set to bypass the error with missing git repo information for the 'preval-build-info' module

ENV PREVAL_BUILD_INFO_PLACEHOLDERS=true

WORKDIR /ferdi

RUN npx lerna init 
RUN npx lerna bootstrap 
RUN cd recipes 
RUN npm i 
RUN npm run package
```

![Screenshot_2021-07-02_00-10-28](https://user-images.githubusercontent.com/755339/124199317-e979e800-dad2-11eb-8ae4-4a269d049171.png)

**Comment by nschonni** [comment]
ARM is not currently supported

**Comment by kzgzhn** [comment]
I'll leave a message for those who are still encountering this problem on ARM processors

I had a similar problem when running npm install it shows an error about the missing file linux-arm64-83_binding.node

In my case, the problem was due to the lack of the required version of python. What caused an attempt to download a ready-made file from GitHub, which did not contain a solution for ARM processors

I found a [working build](https://github.com/sass/node-sass/blob/v4.14.1/.github/workflows/alpine.yml#L36)

The build is based on Alpine images
The installation of python make git gcc g++ is underway, with python of the second version!

My research has shown that it is safe to use images up to and including [alpine3.15](https://pkgs.alpinelinux.org/packages?name=python2&branch=v3.15).

Using [Multi-stage builds](https://docs.docker.com/build/building/multi-stage/), I moved the installation of dependencies to a separate stage
