### ISSUE TITLE
Custom Functions

### ISSUE THREAD

**Issue by mgreter** [sass/node-sass#332]
Hi all

Just wanted to give you a heads up that it should be possible to implement custom functions again. Custom functions are defined inside the dynamic scripting language and then registered with libsass. Then they can be called/referenced from scss/sass files, similar to internal functions. 

Not sure if node-sass had that feature before the libsass refactoring. I fixed [some bits](https://github.com/hcatlin/libsass/pull/181) on libsass so the Perl Bindings, which already had custom functions, would work again. So maybe you can profit off of [that work](https://github.com/mgreter/CSS-Sass/blob/master/lib/CSS/Sass.xs#L215), since both implementations are bindings to a dynamic scripting language. Maybe you also want to expose [sass2scss](https://github.com/mgreter/CSS-Sass/blob/master/lib/CSS/Sass.xs#L344) to convert indented syntax to scss syntax.

There is a new [custom precision](https://github.com/hcatlin/libsass/issues/287) feature, which unfortunately has a regression. I also added the offical spec-tests to the [Perl-Binding test-suite](https://github.com/mgreter/CSS-Sass/blob/master/t/99-sass_specs.t), IMO it would be usefull to include them in node-sass too.

Kind regards
Marcel Greter

**Comment by chriseppstein** [comment]
Hi, this is a critical feature to the extensibility of Sass as users are accustomed to in ruby. I am planning to port a large portion of Compass to node and we need this capability. I have an engineer at my work (linkedin) who is willing to work on this, but he are not accustomed to libsass or node.js's internals so we could really use some pointers about how to get started implementing this feature. As I understand it there are three pieces that are needed here:

* libsass <--> js function binding (in C++)
* Javascript implementation of Sass value objects.
* execution environment and helper functions (exposed as methods and properties of `this`)

Since I wrote a lot of the similar API for ruby, I'd be happy to help define or review the javascript interfaces.

**Comment by xzyfer** [comment]
@mgreter is certainly the person to talk to in regards to the libsass side of things. We have some documentation on the libsass wiki for custom functions that should be of use https://github.com/sass/libsass/wiki/Custom-Functions-internal

**Comment by chriseppstein** [comment]
@xzyfer Ok, I think I get it. So the string passed to `sass_make_function` is a fully qualified sass function argument declaration supporting defaults, etc?

**Comment by xzyfer** [comment]
I'm not entire familiar with the API, but that sounds about right. You might be able to use https://github.com/sass/perl-libsass/blob/8fa1bb0b765bd6b0f1e8391171b09f31eed0c573/lib/CSS/Sass.xs and https://github.com/wellington/wellington as references for using the C API.

Also I'm sure @mgreter will happily help where needed in https://gitter.im/sass

**Comment by am11** [comment]
BTW, this is on [2.1 milestone](https://github.com/sass/node-sass/milestones).

**Comment by am11** [comment]
This is addressed by 07a9540 via #644.
