### ISSUE TITLE
Defining importer function gives Abort trap: 6 error

### ISSUE THREAD

**Issue by browniefed** [sass/node-sass#586]
By simply defining an importer function an Abort trap: 6 gets thrown whenever I attempt to run anything with an import.
```
@import "testimport";
.test {
  color: #000;
}
```

```js
var sass = require('node-sass'),
    path = require('path');

sass.render({
    file: path.resolve(__dirname, './test.scss'),
    outputStyle: 'compressed',
    success: function (css) {
        // the result string
        console.log(css.css);
    },
    error: function(err) {
        console.log(err);
    },
    importer: function(url) {
        return {file: url};
    }
});
```

**Comment by mgreter** [comment]
@am11: First let me be clear: I really think the problem is not in libsass but with (the usage of) libuv. Next: I don't know shit about libuv but tried to hunt down your nasty race condition anyway. So here my uneducated guesses:

The error can also be avoided if this line in `sass_free_context_wrapper` gets commented out: `free(ctx_w);`. But I also don't see why this should error out (it seems valid to deallocate the memory here). Next observation was that commenting out `uv_async_init ...` in `binding.cpp` also "avoids" the crash. I don't know any details about libuv, but I think I know what it should be doing to get this working in an async manner. So I started to wonder where you actually "terminate" the "intermediate" thread. The google search on this lead me to the conclusion that you may miss some `uv_close`calls ...

I guess that's as much as I want to dive into the whole libuv stuff. But I'm pretty convinced that the cluprit is somewhere in there. But I also could be totally wrong here!

As a side note: You should be aware that `uv_work_t`, `uv_mutex_t`, `uv_cond_t` and `uv_async_t` are all direct members to `(sass_context_wrapper) ctx_w`. You seem to pass a lot of pointers to these structs (which is valid) to the internal functions of libuv; ie. `&ctx_w->async`. Once you free `ctx_w`, these pointers will become wild pointers!

**Comment by am11** [comment]
@mgreter, thanks for looking into it.

You are right about `uv_close`, and this was the first thing which @txdv pointed out. I had that fixed with this commit: https://github.com/am11/node-sass/commit/35a82abc79dfd69b265da1751ed8d99e0359c4c9#diff-672b939c4bdf28c42fc7ba5da56105dbR240.

Now with the tip of my master branch, I generated two different sets of logs on Ubuntu:

Valgrind: https://gist.github.com/am11/6cfcebdef05e3751f16d#file-valgrind-log-L151
strace:    https://gist.github.com/am11/ee8e8e1fa2bf39516c15#file-strace-mocha-log-L7680

Both captured the SIGSEGV thrown after running a specific stat-related test and free()'ing the memory.

At libuv IRC channel, someone suggested me to change [calloc call](https://github.com/am11/node-sass/blob/87f9fd59ea2b19b01be6fa390c822a0a788df0fc/src/sass_context_wrapper.cpp#L26) with C++ style memory allocation (`sass_context_wrapper* ctx_w = new sass_context_wrapper;`) and then in dtor, use C++ style `delete` to deallocate `ctx_w`, since C++ takes ref tracking into account (save the masses from double-free()'ing and considered luxury over C in this regard). But it did not work in this scenario, as libsass require us to pass C-style pointer(s) and uses free() to deallocate them, which C++ pointers on free() throw 'invalid pointer' (at least with glibc).

There is [another odd behavior](https://github.com/sass/node-sass/pull/589#issuecomment-68486185) i'm facing when dealing with CLI. I think they might be related (implicitly?). Besides having uv_async_send, uv_cond_wait, uv_mutex, it seems like libuv require some kind of a "push" or another signal to run. According to the [docs](http://nikhilm.github.io/uvbook/threads.html), uv_async_send runs *at least once*! But in this case either the thread is sleeping or there is some kind of a deadlock.

**Comment by kkoopa** [comment]
You should only free the memory from the uv_close callback.
```c++
void uv_close(uv_handle_t* handle, uv_close_cb close_cb)
```

Can for example be done with `uv_close((uv_handle_t*)&ctx_w->async, free);`

**Comment by am11** [comment]
@kkoopa, thanks for your advice. I have applied this patch locally: https://gist.github.com/am11/6b227670e5a827ed2c15.
However, the status of npm tests on Ubuntu is same (segmentation fault after running [first stats](https://github.com/am11/node-sass/blob/master/test/api.js#L471) test and just before starting the next one).

**Comment by am11** [comment]
Hello @browniefed, the TravisCI build is now passing and we will release v2.0.0 :soon:'ish.

I can confirm that the build is pretty ok on both Linux and Windows.

Could you please give it another try (with my master branch) on OSX and confirm if the issue is fixed there?  :)

**Comment by am11** [comment]
Our requirement is bit different and unfortunately that cannot be accomplished by the pure-nan solution. Here is the proof-of-concept how it would look like in pure nan terms: b2da1c7. But it throws exception at `NanAsyncWorker` ctor, when nan tries to NanScope() on the libsass' parser thread (importer_callback). We were facing this exact issue with double lock (our first approach), and hence we had to use `uv_async_send`.

Perhaps it is possible with something other than `NanAsyncWorker`, which I couldn't figure out from examples and elaborated docs.

**Comment by am11** [comment]
@browniefed, I do not have Mac and unfortunately I cannot test darwin binary at this point. So v2.0.0 would probably not be stable for Mac. We will keep this issue open, so in future, anyone with OSX can debug and spot what is wrong there.

Nonetheless, we are at a much better place where we were 10 days ago. So thanks again for reporting this issue! :)

**Comment by am11** [comment]
This is fixed by 0720fa8 and ff53926 via #615. 
All tests are passing on Mac now.
@browniefed confirmed it!

Once again, thanks for everyone who helped us pulling this one off.  :+1:  :tada:

**Comment by callumlocke** [comment]
I just updated to the latest node-sass master, but I still get `Abort trap: 6` when I define an importer function. On OS X 10.9.5.

**Comment by browniefed** [comment]
@callumlocke could you say anything about the process? Did you build custom, or did you let it install the binaries off of node-sass-binaries?

**Comment by callumlocke** [comment]
I just did git pull to get the latest code, then npm install. I didn't do
anything custom.

It works fine until I define an importer function.

**Comment by browniefed** [comment]
@callumlocke please follow this
```
Rebuilding binaries

Node-sass includes pre-compiled binaries for popular platforms, to add a binary for your platform follow these steps:

Check out the project:

git clone --recursive https://github.com/sass/node-sass.git
cd node-sass
git submodule update --init --recursive
npm install
npm install -g node-gyp
node-gyp rebuild  # to make debug release, use -d switch
```

**Comment by callumlocke** [comment]
awesome, thanks
