### ISSUE TITLE
Implement raw css imports

### ISSUE THREAD

**Issue by itajaja** [sass/node-sass#618]
is sass/libsass#754 avaialble with node sass yet?

**Comment by xzyfer** [comment]
No. That feature won't be available until the next version of Libsass.

**Comment by itajaja** [comment]
Thanks for the explanation. Is there a roadmap for the next version?

**Comment by xzyfer** [comment]
Not exactly. We're currently waiting on node-sass to 2.0.0 stable to reach adoption because that's when it'll hit most of our users. Libsass 3.1.0 was a big release so we're leaving some breathing room for bug reports to come in.

Expect a new Libsass release in Feb, and a node-sass release shortly after.

**Comment by itajaja** [comment]
:+1: thanks

**Comment by am11** [comment]
I think we don't have to change anything at node-sass end of this. This feature will appear in future version of node-sass.

**Comment by rach** [comment]
Hi, any idea why it's not currently working with the version of node-sass ( 3.1.2 using libsass 3.2.4 )
I do the import without the file extension.
Thanks.
