### ISSUE TITLE
Publish another beta?

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#642]
Would it be possible to do another beta release, as `2.0.0-beta.2`? There's been some important fixes since then

**Comment by am11** [comment]
No. The next version would be 2.0.0-stable.

**Comment by callumlocke** [comment]
you know semver explicitly allows multiple beta versions? The first one should be `x.x.x-beta`, then others (if necessary) are `x.x.x-beta.2`, etc – see rule 11 on [semver.org](http://semver.org/)

(or if you're saying you just don't want to publish an updated beta, that's your call, but why?)

**Comment by am11** [comment]
Because 2.0.0 stable is ready and there is no point for another beta and redoing the binaries which we are not able to get for the ready version in first place. 
We are waiting for Linux binaries for which we are waiting for some GCC build system expert (black-belt kinda person) to steer our boat in right direction and fix the compatibility issues with old CentOS: https://github.com/sass/node-sass/issues/602 so we don't have another situation like https://github.com/sass/node-sass/issues/517.

**Comment by callumlocke** [comment]
ah I see, thanks for the explanation
