### ISSUE TITLE
Install failing on io.js 1.3 on Windows 8.1 because gyp does not exist

### ISSUE THREAD

**Issue by F21** [sass/node-sass#707]
I am using io.js 1.3 on Windows 8.1 64-bit. Currently, there are no binaries built for io.js 1.3 in https://github.com/sass/node-sass-binaries.

Post install attempts to compile using `pangyp`, however, `pangyp` is not installed because it's not listed in `dependencies` in `package.json`, so the process fails:
````
> node-sass@2.0.1 postinstall D:\test\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module 'D:\test\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:111:16)
    at node.js:799:3
Build failed
````

**Comment by am11** [comment]
> Install failing on io.js 1.3 on Windows 8.1 because gyp does not exist

@F21, that is not the exact reason. We don't want the pangyp step to triggered on end-client system at all but download the prebuild binary, because to build node-sass there are other dependencies as well: VS2013 and python 2.7 etc. 

The real issue here is: In node-sass v2.0.1, we are using strong names to devise the path, which has been fixed by using v8 version. You can find at least four duplicates for what has been done: https://github.com/sass/node-sass/issues?q=is%3Aissue+is%3Aclosed.

Nonetheless; you are right, pangyp is a dev-dependency which should be under dependency, we have plan to refine build process as part of https://github.com/sass/node-sass/issues/683 and address it there. Lets follow the progress there.
