### ISSUE TITLE
Doesn't actually compile my sass files

### ISSUE THREAD

**Issue by lmartins** [sass/node-sass#767]
This might be due to changes in the API, and probably it might be related to gulp-sass. Since im not sure, im reporting here in the hopes someone can clarify that. I've installed `npm install node-sass@3.0.0-alpha.0` inside `node_modules/gulp-sass` The watcher seems to run file, it notices file-changes and runs the gulp Sass task but the build files do not get any of the changes.

Any tips?

**Comment by am11** [comment]
I prepared this gist for grunt-sass reflecting API changes for node-sass v3: https://gist.github.com/am11/47fc07b5d6de73697ee9 (drop-in replacement of `sass.js` in their repo).

I think gulp-sass would also require similar change. Here is the changelog which highlights key changes: https://github.com/sass/node-sass/releases/tag/v3.0.0-pre.

**Comment by am11** [comment]
@dlmanning, on a slightly related note, IMO, you can make use of [`omitSourceMapUrl`](https://github.com/sass/node-sass/#omitsourcemapurl) option instead of [regexing here](https://github.com/dlmanning/gulp-sass/blob/314ce5c1594e541a55e5c5009fb0733c45226567/index.js#L44). I am not sure about your use-case, but normally browsers require this URL to be there to bridge between `.css` and `.map` files. However, the point of the omit option is to provide customisations for mostly non-browser use-cases, such as editor extensions, where the intent is to let user see the CSS preview without source-mapping URL because the URL might be misleading if editor has opted for in-memory operations.

**Comment by lmartins** [comment]
Going to try this later today and post here the result. Thanks Adeel.

**Comment by am11** [comment]
Let me know if I could help. :)
