### ISSUE TITLE
You may not @extend an outer selector from within @media error

### ISSUE THREAD

**Issue by blimmer** [sass/node-sass#823]
I'm getting this error with 3.0.0-beta.4 when I have something as simple as this:

```sass
h1 {
  @extend h2;
}
```

It looks like [others are having this problem as well](https://github.com/sass/node-sass/issues/820#issuecomment-87722700).

**Comment by am11** [comment]
This belongs to libsass: https://github.com/sass/libsass. All syntax related issue belong to libsass.

**Comment by am11** [comment]
See http://sassmeister.com/gist/69d7ec29d7c737365399.

Ruby Sass throws different error. LibSass 3.1.0 does not throw any error. This itself is a bug.

You can prepare a similar gist with steps to reproduce for any such discrepancy you find.

**Comment by blimmer** [comment]
Hmm perhaps I jumped the gun on this issue. I'll try to figure out more about what exactly is going on and open an issue with the appropriate project (if one exists).

**Comment by AW-UC** [comment]
This is issue https://github.com/sass/libsass/issues/943 and might already be fixed. Now it would be a node-sass issue, because it needs to be updated to libsass 3.2.0-beta.4
Please reopen this.

**Comment by aexmachina** [comment]
npm will happily update node-sass to the latest beta because of semver. You might need to `rm -rf node_modules/ember-cli-sass` to get it to upgrade to the latest version. 

However the latest node-sass@3.0.0-beta.4 appears to use libsass@3.2.0-beta.2, so you may want to create an issue on node-sass to update the libsass dependency, because this doesn't use npm (I think they use a Git submodule) so it won't automatically upgrade.

**Comment by AW-UC** [comment]
@aexmachina allright. thanks for clarification.
