### ISSUE TITLE
Feature Reqeust: Store the new `.file` path if an importer returns both `.file` and  `.contents` properties

### ISSUE THREAD

**Issue by jameslnewell** [sass/node-sass#914]
If an importer returns both `.file` and `.contents` properties then use the `.contents` property as the source but store/replace the original `.file` path with the `.file` path returned by the importer. So that, if the `.contents` contained any import statements, the next call to an importer has the correct "resolved" path of the `prev` file.

This is required to [make npm style imports](https://www.npmjs.com/package/sass-composer) work properly. When an importer returns `.contents` for an import with a `file` param using a module name e.g. `sass-grid` and the imported contents contains more import statements e.g. `sass-named-breakpoints`, when the importer is called for the new import statement with a `prev` argument of `sass-grid` which lives somewhere in node_modules, you don't have a usable `prev` path to start looking for the new import contents.

Let me know if I need to explain it clearer.

**Comment by saper** [comment]
Sounds not very difficult, can you post a complete example/test case of how it should work?

**Comment by saper** [comment]
( possibly without composer, just plain node-sass pls)

**Comment by jameslnewell** [comment]
An example of what I'd like  (obviously won't work):

    var sass = require('node-sass');

    var i = 0;
    sass.render(
      {
        file: './index.scss',
        importer: function(file, prev, cb) {

          if (i++ === 0) {
            console.log(prev); //"./index.scss"
            cb({
              file:     './node_modules/sass-grid/mixins.scss",
              contents: '@import "sass-named-breakpoints";'
            });
          } else {
            console.log(prev); //"./node_modules/sass-grid/mixins.scss", not "sass-named-breakpoints"
            cb({
              file:     './node_modules/sass-grid/mixins.scss",
              contents: '.foobar {};' //....could possibly have more imports
            });
          }

        }
      },
      function(err, result) {
        if (err) {
          console.log(err);
        } else {
          console.log(result.css.toString());
        }
      }
    );

The `.file`, `.data` properties to the `.render()` method should probably work the same way for consistency.

**Comment by mattfysh** [comment]
Let me check to see if I understand correctly. You want to be able to call `cb({file: '/a.scss', contents: 'import "b";'})` -- and then when the custom importer is called to resolve "b", the second parameter `prev` comes through as "a.scss".

We've actually managed to have this working for the last week or so, and I think the trick was to reorder the object properties as {contents, file} instead of {file, contents} - let me know if that does the trick!

**Comment by jameslnewell** [comment]
Ah thanks @mattfysh  you're right. The above code works as I hoped. I'm obviously doing something stoopid somewhere else. :blush: 

	prev: stdin
	file: sass-grid
	prev: ./node_modules/sass-grid/mixins.scss
	file: sass-named-breakpoints

Sorry guys.

**Comment by saper** [comment]
I think @jameslnewell didn't try the above, since it has syntax errors :)

I think I get the desired output with the current master

https://gist.github.com/saper/1bd2454399e46afc2707

But I wouldn't bet that recursive importers work well - if you try that more than 4 times you might run into #857 or other similar bugs.

**Comment by jameslnewell** [comment]
noticed that while trying to run it and edited the code :)

**Comment by saper** [comment]
I just realized that my snippet is just another case for #894 - this should not be mistaken with the "correct" results.
